import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-full bg-[#070E18]   bg-[url('/a1.png')]  overflow-x-hidden`}>
             <main>    
              <div className="containerbox">
            {children}
              </div>     
            </main>
      </body>
    </html>
  );
}
